config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins
  #get '/inicio', to: 'welcome#index'

  root "welcome#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  validates :description, :acronym, presence: true
  #Coin pertence a mining_type ou seja Moedas pertecem a tipos de mineração
  belongs_to :mining_type#, optional: true#Deixa o belongs_to opcional na hora de rodar a task dev:setup
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  validates :description, :acronym, presence: true
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#Deixando a tradução em tempo real
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  #layout "adm"
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
#Query params request aula 55
  def index
    # cookies[:curso] = "Usando Cookie"#Guarda os dados no browser
    # session[:curso] = "Usando Session"#Guarda os dados no servidor

    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end
#SHA256:xNLWEwxKWobzPDVs0YX/NhuRUQk2DWrB7LGFHpXmyRo marcoslbrito@hotmail.com

app/helpers/application_helper.rb
module ApplicationHelper
  def locale
      I18n.locale == :en ? "Estados Unidos" : "Portugues do Brasil"#Condicinal ternária
  end

  def data_br(data_usa)
      I18n.locale == :en ? data_usa : data_usa.strftime("%d/%m/%Y")
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
    elsif Rails.env.production?
      "Produção"
    else
      "Teste"
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">

    <strong><%= Coin.human_attribute_name(:description) %>:</strong>
    <%= coin.description %>



    <strong><%= Coin.human_attribute_name(:acronym) %>:</strong>
    <%= coin.acronym %>


    <strong><%= Coin.human_attribute_name(:url_image) %>:</strong>
    <%= image_tag coin.url_image, size: "25x25" %>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image %>
    <%= form.text_field :url_image, class:"form-control", placeholder:"http://img.ur/bitcoin.png" %>
  </div>

  <div class="form-group">
    <%= form.label :mining_type %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blak: 'Selecione...' }, class:"form-control") %>
    <%#= form.select("mining_type_id", MiningType.all.collect {|m| [m.description, m.id] }, {include_blak: 'Selecione...'}) %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t('title.editing_coin') %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t("links.show"), @coin, class:"btn btn-success" %> |
  <%= link_to t("links.back"), coins_path, class:"btn btn-warning" %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>
<%= data_br(Date.today) %>
<h1><%= t('title.coin') %></h1>

<!--
<h2><%#= cookies[:curso] %></h2>
<h2><%#= session[:curso] %></h2>
-->

<div id="coins">
  <% @coins.each do |coin| %>
    <%= render coin %>
    <p>
      <%= link_to t("links.edit"), coin, class:"btn btn-secondary" %> |
      <%= link_to t("links.show"), edit_coin_path(coin), class:"btn btn-success" %> |
      <%= link_to t("links.delete"), coin, method: :delete, form: { data: { turbo_confirm: t("links.confirmation")}}, class:"btn btn-danger" %>
    </p>
  <% end %>
</div>
<br>
<br>
<%= link_to t("links.new_coin"), new_coin_path, class:"btn btn-primary" %> |
<%= link_to t("links.back"), welcome_index_path, class:"btn btn-warning" %>

app/views/coins/new.html.erb
<h1><%= t('title.new_coin') %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t("links.back"), coins_path, class:"btn btn-warning" %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, Coin.human_attribute_name(:description) %>
    <%= text_field_tag nil, @coin.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, Coin.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @coin.acronym, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, Coin.human_attribute_name(:url_image) %>
    <%= text_field_tag nil, @coin.url_image, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
    <%= text_field_tag nil, @coin.mining_type.description, class:"form-control", disabled: true %>
  </div>
</form>

<%#= render @coin %>
<br>
<div>
  <%= link_to t('links.edit'), edit_coin_path(@coin), class:"btn btn-secondary" %> |
  <%= link_to t('links.back'), coins_path, class:"btn btn-warning" %>
  <br>
  <br>
  <%= button_to t('links.delete'), @coin, method: :delete, class:"btn btn-danger" %>
</div>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>CABEÇALHO - ADM</h1>
    <%= yield %>
    <h1>RODAPÉ - ADM</h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller], "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid" >
      <ul class="nav justify-content-end">
        <li>
          <%= link_to '[HOME]', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Potuguês', root_path(locale: 'pt-BR'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'English', root_path(locale: 'en'), class:"nav-link" %>
        </li>
      </ul>
  <!--Mostra qual o controller passo
      <h1>CABEÇALHO - <%#= params[:controller] %></h1>
                                                     -->
      <%= yield %>

    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Proof of Work" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"PoW" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
<!--Utilizando MiningType.human_attribute_name(:description) p/ traduzir o campo usando o atrbuto  -->
    <strong><%= MiningType.human_attribute_name(:description) %>:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong><%= MiningType.human_attribute_name(:acronym) %>:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<h1><%= t('tilte.editing_mining_type') %></h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t("links.show"), @mining_type, class:"btn btn-success" %> |
  <%= link_to t("links.back"), mining_types_path, class:"btn btn-warning" %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('title.mining_type') %></h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to t('links.show_mining_type'), mining_type, class:"btn btn-success" %>
    </p>
  <% end %>
</div>

<%= link_to t('links.new_mining_type'), new_mining_type_path, class:"btn btn-primary" %> |
<%= link_to t("links.back"), welcome_index_path, class:"btn btn-warning" %>

app/views/mining_types/new.html.erb
<h1><%= t('title.new_mining_type') %></h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t("links.back"), mining_types_path, class:"btn btn-warning" %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, MiningType.human_attribute_name(:description) %>
    <%= text_field_tag nil, @mining_type.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, MiningType.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @mining_type.acronym, class:"form-control", disabled: true %>
  </div>
</form>

<%#= render @mining_type %>
<br>
<div>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class:"btn btn-secondary" %> |
  <%= link_to t('links.back'), mining_types_path, class:"btn btn-warning" %>
  <br>
  <br>
  <%= button_to t('links.delete'), @mining_type, method: :delete, class:"btn btn-danger" %>
</div>

app/views/welcome/_menu.html.erb
<%= link_to t('title.coin'), coins_path, class:"btn btn-primary btn-lg", role:"button" %>
<%= link_to t('title.mining_type'), mining_types_path, class:"btn btn-primary btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('title.welcome') %></h1>
  <p class="lead"><%= t('title.msg') %></p>
  <hr class="my-4">
  <p><%= t('title.start') %></p>
  <%= render "menu" %>
</div>
<br>
<!--
<p>
  <%#= link_to 'Português', root_path(locale: 'pt-BR') %>
  <%#= link_to 'Português', '/?locale=pt-BR' %>
</p>
<p>
  <%#= link_to 'English', root_path(locale: 'en') %>
  <%#= link_to 'English', '/?locale=en' %>
</p>
<h1>Seja-Bem Vindo!</h1>

<p>O idioma usado nessa aplicação é: <strong><%#= locale %></strong>. Utilizando Helper</p>
<p>O idioma usado nessa aplicação é: <strong><%#= t('actual_locale') %></strong>. Utilizando I18n</p>

<p>Data: <strong><%#= I18n.l(Date.today) %></strong></p>




<p>
  Você esta em ambiente de <strong><%= ambiente_rails %></strong>
</p>
<p>
  Eu sou a variavel de instância <strong><%#= @meu_nome %></strong>
</p>
<p>
  Estou estudando <strong><%#= @curso %></strong>
</p>
 -->